<?php

namespace Modules\AIContent\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\App;
use Modules\AIContent\Services\OpenAi;
use Modules\AIContent\Repositories\TemplateRepository;
use Modules\AIContent\Repositories\AIContentRepository;

class AIContentController extends Controller
{

    protected $templateRepository;
    protected $contentRepository;

    public function __construct(TemplateRepository $templateRepository, AIContentRepository $contentRepository)
    {
        $this->templateRepository = $templateRepository;
        $this->contentRepository = $contentRepository;
    }

    public function index()
    {
        $contents = $this->contentRepository->getUserContent();
        return view('aicontent::index', compact('contents'));
    }


    public function textGenerator($request)
    {
        if (appMode() || config('app.demo_mode')) {
            $data['results'] = [
                0 => 'For demo mode, Some features will be disabled. For production, this data will be generated by OpenAI.',
            ];
            $data['prompt'] = $request['prompt'];
            $data['status'] = 'success';
            return $data;
        }
        // return $request;
        $open_ai = new OpenAi(config('aicontent.openai_secret_key'));

        $text = '';
        $max_tokens = (int)$request['max_result_length'];
        $counter = 1;
        $max_results = (int)$request['number_of_result'];
        $temperature = (float)$request['creativity'];

        $model = Settings('ai_default_model') ?? 'text-davinci-003';
        if (str_starts_with($model, 'gpt')) {
            $complete = $open_ai->chat([
                'model' => $model,
                'messages' => [
                    [
                        "role" => "system",
                        "content" => "You are an AI assistant that generates LMS (Learning Management System) content."
                    ],
                    [
                        "role" => "user",
                        "content" => $request['prompt']
                    ],
                ],
                'temperature' => $temperature,
                'max_tokens' => $max_tokens,
                'n' => $max_results,
            ]);
        } else {
            $complete = $open_ai->completion([
                'model' => $model,
                'prompt' => $request['prompt'],
                'temperature' => $temperature,
                'max_tokens' => $max_tokens,
                'frequency_penalty' => 0,
                'presence_penalty' => 0,
                'n' => $max_results,
            ]);
        }
        $response = json_decode($complete, true);
         $generated_response = [];
        if (isset($response['choices'])) {
            if (!str_starts_with($model, 'gpt')) {
                if (count($response['choices']) > 1) {
                    foreach ($response['choices'] as $value) {

                        $result = trim($value['text']);
                        $result = str_replace('"', "", $result);
                        $generated_response[] = trim($result);

                        $text .= $counter . '. ' . ltrim($value['text']) . "\r\n\r\n\r\n";
                        $counter++;
                    }
                } else {
                    $result = trim($response['choices'][0]['text']);
                    $result = str_replace('"', "", $result);
                    $generated_response[] = trim($result);

                    $text = $response['choices'][0]['text'];
                }
            } else {
                if (count($response['choices']) > 1) {
                    foreach ($response['choices'] as $value) {
                        $result = trim($value['message']['content']);
                        $result = str_replace('"', "", $result);
                        $generated_response[] = trim($result);

                        $text .= $counter . '. ' . trim($value['message']['content']) . "\r\n\r\n\r\n";
                        $counter++;
                    }
                } else {
                    $result = trim($response['choices'][0]['message']['content']);
                    $result = str_replace('"', "", $result);
                    $generated_response[] = trim($result);

                    $text = ltrim($response['choices'][0]['message']['content']);
                }
            }


            $tokens = $response['usage']['completion_tokens'];

            $data['results'] = $generated_response;
            $data['prompt'] = $request['prompt'];
            $data['text'] = str_replace('"', "", trim($text));
            $data['status'] = 'success';

            $content_data = [
                'user_id' => auth()->user()->id,
                'input_text' => request('keyword'),
                'output_text' => $data['text'],
                'model' => $model,
                'tokens' => $tokens,
                'words' => request('max_result_length'),
                'temperature' => request('creativity'),
                'template_id' => request('template'),
                'lang' => request('language'),
            ];
            $this->saveResult($content_data);
            return $data;
        } elseif (isset($response['error'])) {
            $data['status'] = 'error';
            $data['message'] = $response['error']['message'] ?? _trans('ai-content.Text was not generated, please try again');
            return $data;
        } else {
            $data['status'] = 'error';
            $data['message'] = _trans('ai-content.Text was not generated, please try again');
            return $data;
        }
    }

    public function update(Request $request)
    {
        try {
            $result = $this->contentRepository->updateData($request->all());
            if ($result) {
                Toastr::success(_trans('ai-content.Updated Successfully'), trans('common.Success'));
                return redirect()->back();
            } else {
                Toastr::error(_trans('ai-content.Update Failed'), _trans('common.Error'));
                return redirect()->back();
            }
        } catch (\Throwable $th) {
            GettingError($th->getMessage(), url()->current(), request()->ip(), request()->userAgent());
        }
    }

    function saveResult($response_data)
    {
        try {
            $this->contentRepository->storeData($response_data);
        } catch (\Throwable $th) {
        }
    }

    function commandFormating($data)
    {
        try {
            $template = $data['template'];
            $tone = $data['tone'];
            $keyword = $data['keyword'];

            if ($data['title']) {
                $title = $data['title'];
                $template = str_replace('{title}', $title, $template);
            }

            $template = str_replace('{keywords}', $keyword, $template);
            $template = str_replace('{tone}', trans('ai-content.' . $tone), $template);

            return $template;
        } catch (\Throwable $th) {
            return $th->getMessage();
        }
    }

    function getTemplateMessage($request)
    {
        $template_details = $this->templateRepository->getTemplateDetails($request['template']);
        $template_content = $template_details->template_content->content;
//        $language_code = $request['language'] ?? 'english';
//        App::setLocale($language_code);
        $language = $request['language'] ?? 'english';

        $template_title = "Provide response in " . $language . " language.\n\n ";
        if ($request['title']) {
            $template_title .= "Use {title} as a title.\n\n" . $template_content . ".\n\n " . 'Use following keywords : {keywords}. ' . ".\n\n ";
        } else {
            $template_title .= $template_content . ".\n\n " . 'Use following keywords : {keywords}. ' . ".\n\n ";
        }
        $template_title .= 'Tone of voice must be' . ': {tone}';

        $data['template'] = $template_title;
        $data['tone'] = $request['tone'];
        $data['keyword'] = $request['keyword'];
        $data['title'] = $request['title'];
        $data['max_result_length'] = $request['max_result_length'];
        $data['number_of_result'] = $request['number_of_result'];
        $data['creativity'] = $request['creativity'];

        $command = $this->commandFormating($data);
        $data['prompt'] = $command;
        return $this->textGenerator($data);
    }

    public function generate(Request $request)
    {
        $request = $request->all();
        $result = $this->getTemplateMessage($request);
        return response()->json($result);
    }

    public function delete($id)
    {
        try {
            $result = $this->contentRepository->distroyData($id);
            if ($result) {
                Toastr::success(_trans('ai-content.Deleted Successfully'), trans('common.Success'));
                return redirect()->back();
            } else {
                Toastr::error(_trans('ai-content.Delete Failed'), _trans('common.Error'));
                return redirect()->back();
            }
        } catch (\Throwable $th) {
            GettingError($th->getMessage(), url()->current(), request()->ip(), request()->userAgent());
        }
    }
}
